// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dypynjujbdgmwhgsrtln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cHluanVqYmRnbXdoZ3NydGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODc4NjksImV4cCI6MjA1Nzg2Mzg2OX0.kQq8hd6h_MBy0dlBl9-ibT4FIm8edDt0qJXb34FdWBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);